# Generated by Django 6.0.2 on 2026-04-01 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_contract'),
        ('orders', '0005_alter_orderitem_price_alter_payment_amount'),
    ]

    operations = [
    ]
