# Generated by Django 4.2.7 on 2026-04-03 11:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0007_alter_contract_id_alter_orderitem_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('salary', 'Oylik (Ish haqi)'), ('rent', 'Ijara'), ('materials', 'Xomashyo (Materiallar)'), ('marketing', 'Reklama / Marketing'), ('transport', 'Logistika / Transport'), ('utilities', "Kommunal to'lovlar (Gaz, Svet)"), ('other', 'Boshqa xarajatlar')], default='other', max_length=20, verbose_name='Kategoriya')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Summa')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Sana')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_expenses', to=settings.AUTH_USER_MODEL, verbose_name='Bajaruvchi')),
            ],
            options={
                'verbose_name': 'Xarajat',
                'verbose_name_plural': 'Xarajatlar',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
