# Generated by Django 4.2.7 on 2026-04-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tashqi ID (Click/Payme)'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta'), ('transfer', "Bank o'tkazma"), ('click', 'Click'), ('payme', 'Payme'), ('other', 'Boshqa')], default='cash', max_length=20, verbose_name="To'lov turi"),
        ),
    ]
