# Generated by Django 6.0.2 on 2026-02-27 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='Miqdor')),
                ('min_quantity', models.IntegerField(default=5, verbose_name='Minimal miqdor')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='products.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Qoldiq',
                'verbose_name_plural': 'Ombor qoldiqlari',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'Kirim'), ('out', 'Chiqim'), ('adjust', 'Tuzatish')], max_length=10, verbose_name='Tur')),
                ('quantity', models.IntegerField(verbose_name='Miqdor')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='Sabab')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sana')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kim tomonidan')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='products.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Harakat',
                'verbose_name_plural': 'Ombor harakatlari',
                'ordering': ['-created_at'],
            },
        ),
    ]
