# Generated by Django 6.0.2 on 2026-03-11 07:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_telegram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Format: +998(90) 123-45-67', max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Telefon formati: +998(90) 123-45-67', regex='^\\+998\\(\\d{2}\\) \\d{3}-\\d{2}-\\d{2}$')], verbose_name='Telefon'),
        ),
    ]
