# Generated by Django 6.0.2 on 2026-03-03 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_fields'),
        ('clients', '0003_client_archive'),
    ]

    operations = [
    ]
