# Generated by Django 6.0.2 on 2026-03-04 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_merge_0002_client_fields_0003_client_archive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='mfy',
            field=models.CharField(blank=True, max_length=150, verbose_name='MFY'),
        ),
    ]
