# Generated by Django 6.0.2 on 2026-03-11 07:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_alter_client_mfy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(help_text='Format: +998(90) 123-45-67', max_length=20, validators=[django.core.validators.RegexValidator(message='Telefon formati: +998(90) 123-45-67', regex='^\\+998\\(\\d{2}\\) \\d{3}-\\d{2}-\\d{2}$')], verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone2',
            field=models.CharField(blank=True, help_text='Format: +998(90) 123-45-67', max_length=20, validators=[django.core.validators.RegexValidator(message='Telefon formati: +998(90) 123-45-67', regex='^\\+998\\(\\d{2}\\) \\d{3}-\\d{2}-\\d{2}$')], verbose_name="Qo'shimcha telefon"),
        ),
    ]
