# Generated by Django 6.0.2 on 2026-03-11 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_alter_client_phone_alter_client_phone2'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='total_spent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Jami sarflangan summa'),
        ),
    ]
