# Generated by Django 4.2.7 on 2026-04-11 16:42

import apps.clients.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_client_total_spent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=apps.clients.models.client_avatar_path, verbose_name='Rasm'),
        ),
    ]
